server:
  port: 8001

spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  thymeleaf:
    prefix: classpath:/template/
    check-template-location: true
    suffix: .html
    mode: HTML
    encoding: UTF-8
    context-type: text/html
    cache: false
  application:
    name: cloud-data-cache-service

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    #表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: true
    #说是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka:eurekaBigdata@eureka01.prod:8081/eureka,http://eureka:eurekaBigdata@eureka02.prod:8082/eureka,http://eureka:eurekaBigdata@eureka03.prod:8083/eureka